package com.example.android.miwok;

class Word {

    /**
     * Default translation for the word
     */
    private String mDefaultTranslation;

    /**
     * Miwok translation for the word
     */
    private String mMiwokTranslation;

    /**
     * Image resource ID for the image associated with the word
     */
    private int mImageResourceId;

    /**
     * Create a new Word object
     *
     * @param miwokTranslation   a String for the word in Miwok language
     * @param defaultTranslation a String for the word in the language that the user understands
     */
    Word(String defaultTranslation, String miwokTranslation) {
        this(defaultTranslation, miwokTranslation, 0);
    }

    /**
     * Create a new Word object
     *
     * @param defaultTranslation a String for the word in the language that the user understands
     * @param miwokTranslation a String for the word in Miwok language
     * @param imageResourceId an int for the drawable resource ID for the image associated with the word
     */
    Word(String defaultTranslation, String miwokTranslation, int imageResourceId) {
        this.mDefaultTranslation = defaultTranslation;
        this.mMiwokTranslation = miwokTranslation;
        this.mImageResourceId = imageResourceId;
    }

    /**
     * Get the default translation of the word
     *
     * @return a String for the default translation
     */
    String getDefaultTranslation() {
        return mDefaultTranslation;
    }

    /**
     * Get the miwok translation of the word
     *
     * @return a String for the miwok translation
     */
    String getMiwokTranslation() {
        return mMiwokTranslation;
    }

    /**
     * Get image file's resource ID
     *
     * @return an int value for the resource ID that is generated by the R class
     */
    int getImageResourceId() {
        return mImageResourceId;
    }
}
